<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'DTS\\eBaySDK\\Trading\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\Shopping\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\ReturnManagement\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\ResolutionCaseManagement\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\MerchantData\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\HalfFinding\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\Finding\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\FileTransfer\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\BusinessPoliciesManagement\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\BulkDataExchange\\Mocks\\' => array($vendorDir . '/dts/ebay-sdk-php/test'),
    'DTS\\eBaySDK\\' => array($vendorDir . '/dts/ebay-sdk-php/src'),
);
